<?php

/**
 * @file
 * Contains hook implementations for the Hyphens Control module.
 */

/**
 * Implements hook_page_attachments().
 *
 * Attaches the global hyphens disabling library when enabled in configuration.
 */
function hyphens_control_page_attachments(array &$attachments) {
  $config = \Drupal::config('hyphens_control.settings');

  if ($config->get('global_disable')) {
    $attachments['#attached']['library'][] = 'hyphens_control/global';
  }
}

